### ISSUE TITLE
npm install fails with 'no exported member 'CellNick''

### ISSUE THREAD

**Issue by robot5x** [eyss/elemental-chess#12]
Cloned repo, successfully entered nix-shell.
`npm install`
results in
```
npm ERR! code 2
npm ERR! git dep preparation failed
npm ERR! command /nix/store/p6h1iz5lcvfz1hg1z497ypa22rv52xxx-nodejs-16.8.0/bin/node /nix/store/p6h1iz5lcvfz1hg1z497ypa22rv52xxx-nodejs-16.8.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/alex/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > @holochain/tryorama@0.4.5 prepare
npm ERR! > npm run build
npm ERR! 
npm ERR! 
npm ERR! > @holochain/tryorama@0.4.5 build
npm ERR! > rm -rf ./lib ; tsc -d
npm ERR! 
npm ERR! src/cell.ts(1,18): error TS2305: Module '"../node_modules/@holochain/conductor-api/lib"' has no exported member 'CellNick'.
npm ERR! src/conductor.ts(10,3): error TS2305: Module '"../node_modules/@holochain/conductor-api/lib"' has no exported member 'CellNick'.
npm ERR! src/conductor.ts(279,7): error TS2322: Type '{ hash: Buffer; nick: string; }[]' is not assignable to type 'InstallAppDnaPayload[]'.
npm ERR!   Property 'role_id' is missing in type '{ hash: Buffer; nick: string; }' but required in type 'InstallAppDnaPayload'.
npm ERR! src/conductor.ts(326,48): error TS2339: Property 'cell_nick' does not exist on type 'InstalledCell'.
npm ERR! src/player.ts(8,35): error TS2305: Module '"../node_modules/@holochain/conductor-api/lib"' has no exported member 'CellNick'.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 2
npm ERR! npm ERR! path /home/alex/.npm/_cacache/tmp/git-cloneffmmi6
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/alex/.npm/_logs/2021-12-01T19_05_17_365Z-debug.log
```

**Comment by guillemcordoba** [comment]
@robot5x thanks! Could you try again with the latest main branch? Just updated everything to hc 0.0.118.

**Comment by robot5x** [comment]
thanks @guillemcordoba. I pulled latest main, entered nix-shell successfully, and npm install now returns:
`npm ERR! Cannot read properties of undefined (reading 'extraneous')`
Log file output:
```
0 verbose cli [
0 verbose cli   '/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/bin/node',
0 verbose cli   '/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.0.0
2 info using node@v16.11.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/data/holochain/elemental-chess/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/alex/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 14ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree Completed in 688ms
29 timing command:install Completed in 704ms
30 verbose stack TypeError: Cannot read properties of undefined (reading 'extraneous')
30 verbose stack     at Arborist.[loadVirtualLink] (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:308:30)
30 verbose stack     at Arborist.[resolveLinks] (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:218:34)
30 verbose stack     at async Arborist.[loadFromShrinkwrap] (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:98:5)
30 verbose stack     at async Arborist.loadVirtual (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:71:5)
30 verbose stack     at async Arborist.buildIdealTree (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:212:7)
30 verbose stack     at async Promise.all (index 1)
30 verbose stack     at async Arborist.reify (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:148:5)
30 verbose stack     at async Install.install (/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/lib/node_modules/npm/lib/install.js:170:5)
31 verbose cwd /data/holochain/elemental-chess
32 verbose Linux 5.15.4-arch1-1
33 verbose argv "/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/bin/node" "/nix/store/hqf2bdprlk4d0300495pwsd7dm7a2w41-nodejs-16.11.1/bin/npm" "install"
34 verbose node v16.11.1
35 verbose npm  v8.0.0
36 error Cannot read properties of undefined (reading 'extraneous')
37 verbose exit 1
```

**Comment by guillemcordoba** [comment]
Wow that's weird. Does not happen for me. Maybe try these solutions? https://stackoverflow.com/questions/66729098/npm-err-cannot-read-property-extraneous-of-undefined

**Comment by robot5x** [comment]
ah yes it was an issue with my npm files so the last issue was my fault. All good now - thanks for your help!
